title: BLFY's Blog
description: 个人博客
url: "https://jyh9521.github.io"
baseurl: ""

theme: minima

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
